language: node_js
node_js: 
  - "stable"

# Cache
cache:
  bundler: true
  directories:
    - "$HOME/.npm"
    - "node_modules"

env:
  global:
    - TEST_USER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyNzkyNGI2LTk4OTQtMTFlNS1iZTM4LTAwMWQ0MmVmYTMxOCIsImlzQWRtaW4iOmZhbHNlLCJmaXJzdE5hbWUiOiJBcnJ5IiwibGFzdE5hbWUiOiJQb3J0ZXIiLCJlbWFpbCI6ImF5YW5mZUBnbWFpbC5jb20iLCJnZW5kZXIiOiJtYWxlIiwiam9iUm9sZSI6IkRlc2lnbmVyIiwiZGVwYXJ0bWVudCI6IlVzZXIgRXhwZXJpZW5jZSIsImFkZHJlc3MiOiIxLCBTb21lIHN0cmVldCwgcmFuZG9tIGVzdGF0ZSwgTGFnb3MuIiwiaWF0IjoxNTc0NTk0MjM3LCJleHAiOjE2NjA5OTQyMzd9.r5j_8qPLjCsaid6eFR9u0Z9bM4wxMzClrtH_ro7f7Hk
    - TEST_ADMIN_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc5MTIyNGI2LTk4OTQtMTFlNS1iZTM4LTAwMWQ0MmU4ZWYzMSIsImlzQWRtaW4iOnRydWUsImZpcnN0TmFtZSI6IkZlcmFubWkiLCJsYXN0TmFtZSI6IkFraW5sYWRlIiwiZW1haWwiOiJmZXJhbm1pYWtpbmxhZGVAZ21haWwuY29tIiwiZ2VuZGVyIjoiZmVtYWxlIiwiam9iUm9sZSI6IkZyb250ZW5kIEVuZ2luZWVyIiwiZGVwYXJ0bWVudCI6IkZyb250ZW5kIiwiYWRkcmVzcyI6IjIsIHJhbmRvbSBzdHJlZXQsIHNvbWUgYXJlYSwgTGFnb3MuIiwiaWF0IjoxNTc0NjI2NzU2LCJleHAiOjE2NjEwMjY3NTZ9.2Z9dLuZ3nN6NmNCR7rhwhdA3g3rSnQqM4cpTcJ_VOOs
  #jobs:
    #- USE_NETWORK=true


install:
  - npm install                         # Install npm dependencies

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug
  
# Run the test suites
script:
  - npm test                            # Frontend linting & specs

# Pipe the coverage data to Code Climate
after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
